spring.application.name=HertzEcke-Backend

spring.datasource.url=jdbc:mysql://localhost:3306/hertzecke?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

spring.datasource.username=root
spring.datasource.password=amirreza082004
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true